Use configurable accepted range in questionnaire float comparison
apluslms/mooc-grader pull request #143
Opened 2023-04-03 07:36 UTC by ihalaij1

# Description

**What?**

Floating point comparison tolerance in freetext questionnaires can now be configured with two variables ``float_rel_tol`` and ``float_abs_tol``. This change requires changes in the a-plus-rst-tools freetext directive too: https://github.com/apluslms/a-plus-rst-tools/issues/158

**Why?**

With the previous hardcoded value of 2%, the float comparison has been basically unusable on courses in which 2% includes far too wide a range of solutions.

Fixes #140

# Testing

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [ ] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [x] Manual testing.

Tested that float comparison questionnaires work with both new variables.

**Did you test the changes in**

- [x] Chrome
- [ ] Firefox
- [ ] This pull request cannot be tested in the browser.

# Translation

- [ ] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [x] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [ ] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

2023-05-11 18:18 UTC, PasiSa requested changes
Looks straight forward to me, only a couple of small comments. I didn't test it, but I assume you have done so.

2023-05-11 18:18 UTC, PasiSa commented on access/types/forms.py
> +    def compare_values(self, method, val, cmp, float_rel_tol=1e-09, float_abs_tol=0.0):
Because the old code used 0.02, shouldn't the default also be 0.02, to maintain backwards compatibility?

2023-05-12 07:15 UTC, ihalaij1 commented on access/types/forms.py
> +                kwargs = {}
Good point! I fixed this.

2023-06-09 15:48 UTC, Mankro approved these changes
Good!

2023-06-09 15:48 UTC, merged