Improve generic feedback on pick-any questions
apluslms/mooc-grader pull request #151
Opened 2023-08-09 05:45 UTC by ihalaij1

# Description

**What?**

Add an additional feedback note on pick-anys when partial-points option is not used and the answer is incorrect.

![image](https://github.com/apluslms/mooc-grader/assets/38466145/02c7a475-3d1d-4c51-976f-41aa4cd13143)

**Why?**

Students sometimes assume that zero points means “nothing is correct”; moreover, they sometimes expect to get partial credit.

Fixes #150

# Testing

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [ ] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [x] Manual testing.

Tested that the new feedback note only shows in pick-any questions without partial-points option when the answer is incorrect.

**Did you test the changes in**

- [x] Chrome
- [ ] Firefox
- [ ] This pull request cannot be tested in the browser.

# Translation

- [x] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [x] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [ ] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

2023-08-09 05:48 UTC, ihalaij1 commented
I noticed that the note admonition is not displayed as a blue box on the individual exercise page (the CSS class is missing there?).
Is this minor problem something that needs to be fixed?

2023-08-10 16:17 UTC, Mankro commented
> I noticed that the note admonition is not displayed as a blue box on the individual exercise page (the CSS class is missing there?). Is this minor problem something that needs to be fixed?

That is because the styles for the HTML class `admonition note` are only defined in the default.css file in A-plus-rst-tools:
https://github.com/apluslms/a-plus-rst-tools/blob/9894bb18ca9a940455a132275b5ce7366847582a/theme/aplus/static/default.css#L53-L59

The A-plus-rst-tools styles only affect chapter pages since they are rendered to HTML by the rst tools (Sphinx).

This problem can be fixed by using the existing questionnaire feedback styles instead of adding a new info admonition. I would prefer to use the existing styles anyway.

2023-08-10 16:26 UTC, Mankro requested changes
I think the message could be added as an additional feedback item to the question. Now, you have added a separate implementation for a very specific message that is functionally similar to feedback items, but it is implemented and rendered completely differently than the other feedback items. In addition, I feel that the blue info box is too verbose and takes a lot of space on the screen. If it were rendered like other feedback items, it would blend in better and simply consume less screen space.

You don't need to change any HTML template since they already render the hints. You just add this new hint in the questionnaire grading code when the checkbox question is not answered correctly and the `partial_points` setting is disabled.

Take a look at how the existing note HINT_MULTIPLE_CHOICES_SELECTABLE has been added:
https://github.com/apluslms/mooc-grader/blob/a86071f57a1403e9650d7465b196af41a4b577f7/access/types/forms.py#L684

In the same `grade_field` function, you can add the new hint. You can use the same django.po messages you already added. The function already has access to the settings like `partial_points` and it knows if the checkbox question was answered correctly.

2023-08-11 10:15 UTC, ihalaij1 commented
I made changes according to the requests you made. If multiple hints are displayed, the new hint always appears last.
Here's how it looks now:
![image](https://github.com/apluslms/mooc-grader/assets/38466145/a22a0041-dda7-4f7f-9839-ad19d7de28c8)

2023-08-11 12:17 UTC, Mankro approved these changes
Looks great!

2023-08-11 12:39 UTC, Mankro commented
I changed the git commit message and force-pushed.

2023-08-11 12:39 UTC, merged

2023-08-11 12:46 UTC, Mankro commented
I now noticed that the original issue requested a slightly different trigger for the new hint:

> IMO, it would be a good idea to insert an additional feedback bullet on pick-anys, to be displayed whenever a student’s answer is partially correct (i.e., something was right, but not everything).

In this pull request, the hint is triggered even if the submission is not partially correct, but completely incorrect. However, I don't think this is an important distinction. After all, it is easy to make partially correct submissions since only one checkbox needs to be in the correct state in order to make it "partially" correct. Each checkbox is either ticked or not ticked. If the student leaves one easy obviously incorrect choice unticked, that already makes it a partially correct submission.

2023-08-14 11:32 UTC, jsorva commented
Looks good to me, thanks @ihalaij1 and @Mankro!