Display a warning when submission feedback is too large
apluslms/mooc-grader pull request #152
Opened 2023-08-11 08:15 UTC by ihalaij1

# Description

**What?**

The grading-base sends an additional ``feedback_size_error`` field to the MOOC-Grader when the feedback for a submission is too large. This is now used to determine if a warning about long feedback length should be displayed to a student.

**Why?**

If an assignment grader prints massive amounts of text to the feedback, saving it to A+ fails. This happens especially when the student's own print outputs are included in the feedback and the student prints lots of data in a loop. In these cases, A+ should show useful feedback to the student that warns about the massive feedback and advises them to avoid printing extra output.

Fixes #146

# Testing

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [ ] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [x] Manual testing.

Tested that submissions with very large feedback now display an informative error message in A+ instead of getting stuck in grading.

**Did you test the changes in**

- [x] Chrome
- [ ] Firefox
- [ ] This pull request cannot be tested in the browser.

# Translation

- [x] Did you modify or add new strings in the user interface?

# Programming style

- [x] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [ ] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

2023-08-11 14:06 UTC, Mankro requested changes
Looks good, but answer the questions below first.

2023-08-11 14:16 UTC, ihalaij1 commented on access/views.py
> +    if request.POST.get("feedback_size_error"):
Currently, grading-base sets the value to a string ``"true"`` or doesn't set it at all. A ``"false"`` string would enter the if-branch too. Do you want me to change it to be more explicit, i.e. ``if request.POST.get("feedback_size_error") == "true":``?

2023-08-11 14:17 UTC, ihalaij1 commented on locale/en/LC_MESSAGES/django.po
> +"Your code may be stuck in an infinite loop or outputs a large amount of data "
I can make that change that after you respond to the above question too.

2023-08-11 17:58 UTC, Mankro commented on access/views.py
> +    if request.POST.get("feedback_size_error"):
Yeah, let's be explicit with the "boolean".

2023-08-14 13:38 UTC, Mankro approved these changes

2023-08-14 13:39 UTC, merged